wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1682663262.801776
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 40
img_scale:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 0.0001
n_units:
  desc: null
  value: 2
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
